### ISSUE TITLE
Type QuantityDecorator is not exported

### ISSUE THREAD

**Issue by ghost** [MRVDH/picnic-api#11]
First of all, thanks for providing this library! While using it I noticed that all types in `src/types/picnic-api.ts` are exposed except `QuantityDecorator`, see [here](https://github.com/MRVDH/picnic-api/blob/32e294dab20d28bb4b6d391b48d034a4cc374216/src/types/picnic-api.ts#L102).

**Comment by christof-mathies** [comment]
Pull request https://github.com/MRVDH/picnic-api/pull/12 address this issue.

**Comment by MRVDH** [comment]
Quick update: I've added the fix for this and planning to release it tomorrow! 😄

**Comment by MRVDH** [comment]
Fixed in release: https://github.com/MRVDH/picnic-api/releases/tag/v3.1.0
