### ISSUE TITLE
getDeliveryPosition() endpoint not working

### ISSUE THREAD

**Issue by lavolp3** [MRVDH/picnic-api#3]
I tried the endpoint today with a current delivery. Never got a positive response. Here the error
```
<error> Error in getDeliveryPosition function: 
<error> 422: Unprocessable Entity
<error> 'tech.picnic.store.mobileapi.support.usercontext.UserContextInfo' context is not present
```

**Comment by MRVDH** [comment]
Known issue unfortunately! I haven't been able to figure out how to get it to work. I recently learned that the most recent api version is 17 instead of 15, so I'm going to update it soon and give this route another try. Will keep you updated 👍

**Comment by lavolp3** [comment]
Great! Looking forward to it.

**Comment by MRVDH** [comment]
New release! https://github.com/MRVDH/picnic-api/releases/tag/v1.4.0

GetDeliveryPostion returns some scenario info. Then, with GetDeliveryScenario you can get the full delivery status, such as the driver, the route the car takes (latitude longitude) and more.

Let me know if you experience any issues 👍

**Comment by MRVDH** [comment]
Fixed an issue where some other requests didn't work anymore. Make sure to use 1.4.1 👍

**Comment by GijsvanDulmen** [comment]
Do you perhaps have some examples of what is to be expected as response? Otherwise I would need to wait before the next delivery to record the details :-) Probably a good thing to log it over here as well.

**Comment by MRVDH** [comment]
Here an example of what `getDeliveryPosition` and `getDeliveryScenario` return. I anonymized most of the data.

`scenario_ts` is the current scenario id of the scenario list in `getDeliveryScenario`.
the `scenario` list is the list of waypoints that the car moves along.

I'll also add this to the docs soon.

getDeliveryPosition
```js
{
    "version": 1,
    "scenario_ts": 1234567891,
    "eta": 123456789,
    "eta_window": {
      "start": "2021-03-06T09:20:000+01:00",
      "end": "2021-03-06T12:00:000+01:00"
    },
    "query_interval": 10000
}
```

getDeliveryScenario
```js
{
    "version": 1,
    "destination": {
      "house_number": 100,
      "house_number_ext": "",
      "postcode": "1234AB",
      "street": "Streetname",
      "city": "Amsterdam"
    },
    "driver": {
      "name": "Name of driver",
      "photo_url": "https://prp-image-manager-prod.s3.amazonaws.com/runners/runnerId/small.png",
      "quote": "Their quote"
    },
    "scenario": [
      {
        "ts": 1234567891,
        "lat": 51.00001,
        "lng": 4.00001
      },
      {
        "ts": 1234567892,
        "lat": 51.00002,
        "lng": 4.00001
      },
      {
        "ts": 1234567893,
        "lat": 51.00002,
        "lng": 4.00003
      }
    ],
    "vehicle": {
      "name": "PICNIC_EPV",
      "image": "base64 string of the car image"
    }
}
```

**Comment by GijsvanDulmen** [comment]
And the "eta" field in the position is the number of minutes or seconds till delivery? This would really make my home automation integration of Picnic nice! :-) Making sure we have all the bags and bottles collected before the driver rings the doorbell.. haha!

**Comment by MRVDH** [comment]
> And the "eta" field in the position is the number of minutes or seconds till delivery?

I haven't used it yet, but it's a unix timestamp, so you could put it in a new Date() and then check exactly what it is.

**Comment by lavolp3** [comment]
I got a delivery today :-) The eta in the delivery_position is a timestep of the most detailed eta. 
It was 2:50 pm for me and they ringed the bell around 4-5 minutes later.  

delivery_scenario contained driver's name :-) and a super-detailed array of positions over time. It started to record roughly 45 min before delivery. Before that the `deliveryPosition` call returned empty ata and the `deliveryScenario` call returned a 404 NOT FOUND error
