### ISSUE TITLE
Deletion of the `POST /api/{api}/deliveries` endpoint

### ISSUE THREAD

**Issue by Stephan202** [MRVDH/picnic-api#5]
Hi @MRVDH! Just a heads-up: Picnic plans to drop (without replacement) the `POST /api/{api}/deliveries` endpoint in the coming 1-2 weeks, thereby dropping support for [`PicnicClient.getDeliveries(false)`](https://github.com/MRVDH/picnic-api/blob/a2aebbdbdca8bff06198fb3e49fd8ed678f06878/index.js#L208-L215).

(The `POST /api/{api}/deliveries/summary` endpoint remains functional.)

**Comment by MRVDH** [comment]
@Stephan202 that's great info! I will release a fix for this somewhere within the next 5-7 days, thanks! 👍

**Comment by MRVDH** [comment]
@Stephan202 I've opened up a PR that I will merge tomorrow, with this change in it.

PS. Out of curiosity, I am unable to find the `GET /product/{product_id}` route in the decompiled android code. Any idea if this was renamed, obfuscated or deprecated in some way, if you are at liberty to share of course. 👍
